// <auto-generated />
using D20Market.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D20Market.Migrations
{
    [DbContext(typeof(D20MarketContextDb))]
    [Migration("20250515211703_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("D20Market.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Backstory")
                        .HasColumnType("TEXT");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Backstory = "This is the backstory for your Character1",
                            Charisma = 15,
                            Class = "Fighter",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 2,
                            Name = "Character1",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 2,
                            Backstory = "This is the backstory for your Character2",
                            Charisma = 15,
                            Class = "Cleric",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 3,
                            Name = "Character2",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 3,
                            Backstory = "This is the backstory for your Character3",
                            Charisma = 15,
                            Class = "Rogue",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 4,
                            Name = "Character3",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 4,
                            Backstory = "This is the backstory for your Character4",
                            Charisma = 15,
                            Class = "Ranger",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 5,
                            Name = "Character4",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 5,
                            Backstory = "This is the backstory for your Character5",
                            Charisma = 15,
                            Class = "Wizard",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 6,
                            Name = "Character5",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 6,
                            Backstory = "This is the backstory for your Character6",
                            Charisma = 15,
                            Class = "Fighter",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 7,
                            Name = "Character6",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 7,
                            Backstory = "This is the backstory for your Character7",
                            Charisma = 15,
                            Class = "Cleric",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 8,
                            Name = "Character7",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 8,
                            Backstory = "This is the backstory for your Character8",
                            Charisma = 15,
                            Class = "Rogue",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 9,
                            Name = "Character8",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 9,
                            Backstory = "This is the backstory for your Character9",
                            Charisma = 15,
                            Class = "Ranger",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 10,
                            Name = "Character9",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 10,
                            Backstory = "This is the backstory for your Character10",
                            Charisma = 15,
                            Class = "Wizard",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 11,
                            Name = "Character10",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 11,
                            Backstory = "This is the backstory for your Character11",
                            Charisma = 15,
                            Class = "Fighter",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 12,
                            Name = "Character11",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 12,
                            Backstory = "This is the backstory for your Character12",
                            Charisma = 15,
                            Class = "Cleric",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 13,
                            Name = "Character12",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 13,
                            Backstory = "This is the backstory for your Character13",
                            Charisma = 15,
                            Class = "Rogue",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 14,
                            Name = "Character13",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 14,
                            Backstory = "This is the backstory for your Character14",
                            Charisma = 15,
                            Class = "Ranger",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 15,
                            Name = "Character14",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 15,
                            Backstory = "This is the backstory for your Character15",
                            Charisma = 15,
                            Class = "Wizard",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 16,
                            Name = "Character15",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 16,
                            Backstory = "This is the backstory for your Character16",
                            Charisma = 15,
                            Class = "Fighter",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 17,
                            Name = "Character16",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 17,
                            Backstory = "This is the backstory for your Character17",
                            Charisma = 15,
                            Class = "Cleric",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 18,
                            Name = "Character17",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 18,
                            Backstory = "This is the backstory for your Character18",
                            Charisma = 15,
                            Class = "Rogue",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 19,
                            Name = "Character18",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 19,
                            Backstory = "This is the backstory for your Character19",
                            Charisma = 15,
                            Class = "Ranger",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 20,
                            Name = "Character19",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 20,
                            Backstory = "This is the backstory for your Character20",
                            Charisma = 15,
                            Class = "Wizard",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 1,
                            Name = "Character20",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 21,
                            Backstory = "This is the backstory for your Character21",
                            Charisma = 15,
                            Class = "Fighter",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 2,
                            Name = "Character21",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 22,
                            Backstory = "This is the backstory for your Character22",
                            Charisma = 15,
                            Class = "Cleric",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 3,
                            Name = "Character22",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 23,
                            Backstory = "This is the backstory for your Character23",
                            Charisma = 15,
                            Class = "Rogue",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 4,
                            Name = "Character23",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 24,
                            Backstory = "This is the backstory for your Character24",
                            Charisma = 15,
                            Class = "Ranger",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = true,
                            Level = 5,
                            Name = "Character24",
                            PlayerId = 1,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        },
                        new
                        {
                            CharacterId = 25,
                            Backstory = "This is the backstory for your Character25",
                            Charisma = 15,
                            Class = "Wizard",
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            IsPublic = false,
                            Level = 6,
                            Name = "Character25",
                            PlayerId = 2,
                            Race = "Elf",
                            Strength = 10,
                            Wisdom = 11
                        });
                });

            modelBuilder.Entity("D20Market.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Email = "player1@example.com",
                            Name = "Alice"
                        },
                        new
                        {
                            PlayerId = 2,
                            Email = "player2@example.com",
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("D20Market.Models.Character", b =>
                {
                    b.HasOne("D20Market.Models.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("D20Market.Models.Player", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
