// <auto-generated />
using D20Market.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D20Market.Migrations
{
    [DbContext(typeof(D20MarketContextDb))]
    partial class D20MarketContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("D20Market.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Backstory")
                        .HasColumnType("TEXT");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.HasIndex("ClassId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("D20Market.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            Name = "Barbarian"
                        },
                        new
                        {
                            ClassId = 2,
                            Name = "Bard"
                        },
                        new
                        {
                            ClassId = 3,
                            Name = "Cleric"
                        },
                        new
                        {
                            ClassId = 4,
                            Name = "Druid"
                        },
                        new
                        {
                            ClassId = 5,
                            Name = "Fighter"
                        },
                        new
                        {
                            ClassId = 6,
                            Name = "Monk"
                        },
                        new
                        {
                            ClassId = 7,
                            Name = "Paladin"
                        },
                        new
                        {
                            ClassId = 8,
                            Name = "Ranger"
                        },
                        new
                        {
                            ClassId = 9,
                            Name = "Rogue"
                        },
                        new
                        {
                            ClassId = 10,
                            Name = "Sorcerer"
                        },
                        new
                        {
                            ClassId = 11,
                            Name = "Warlock"
                        },
                        new
                        {
                            ClassId = 12,
                            Name = "Wizard"
                        });
                });

            modelBuilder.Entity("D20Market.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Email = "player1@example.com",
                            Name = "Alice"
                        },
                        new
                        {
                            PlayerId = 2,
                            Email = "player2@example.com",
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("D20Market.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            Name = "Human"
                        },
                        new
                        {
                            RaceId = 2,
                            Name = "Elf"
                        },
                        new
                        {
                            RaceId = 3,
                            Name = "Dwarf"
                        },
                        new
                        {
                            RaceId = 4,
                            Name = "Halfling"
                        },
                        new
                        {
                            RaceId = 5,
                            Name = "Orc"
                        },
                        new
                        {
                            RaceId = 6,
                            Name = "Tiefling"
                        },
                        new
                        {
                            RaceId = 7,
                            Name = "Dragonborn"
                        },
                        new
                        {
                            RaceId = 8,
                            Name = "Gnome"
                        },
                        new
                        {
                            RaceId = 9,
                            Name = "Half-Elf"
                        },
                        new
                        {
                            RaceId = 10,
                            Name = "Half-Orc"
                        });
                });

            modelBuilder.Entity("D20Market.Models.Character", b =>
                {
                    b.HasOne("D20Market.Models.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D20Market.Models.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D20Market.Models.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Player");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("D20Market.Models.Class", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("D20Market.Models.Player", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("D20Market.Models.Race", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
